---
- hosts: all
  gather_facts: no

  vars_files:
    - defaults.yml

  tasks:
#  - import_tasks: tasks/test.yml

    - import_tasks: tasks/zsh.yml
      when: configure_zsh
      tags: ['zsh-cfg']

    - import_tasks: tasks/tmux.yml
      when: configure_tmux
      tags: ['tmux-cfg']

    - import_tasks: tasks/vim.yml
      when: configure_vim
      tags: ['vim-cfg']

    - import_tasks: tasks/nvim.yml
      when: configure_nvim
      tags: ['nvim-cfg']

#    - import_tasks: tasks/sshrc.yml
#      when: configure_sshrc
#      tags: ['sshrc-cfg']


#
#  tasks:
#    - include_tasks: "{{ item }}"
#      with_fileglob:
#        - "./tasks/*.yml"

#     pre_tasks:
#       - name: Include playbook configuration.
#         include_vars: "{{ item }}"
#         with_fileglob:
#           - "{{ playbook_dir }}/config.yml"
#         tags: ['always']
#
#     roles:
#       - role: elliotweiser.osx-command-line-tools
#       - role: geerlingguy.mac.homebrew
#         tags: ['homebrew']
#
#     tasks:
#       - import_tasks: tasks/sudoers.yml
#         when: configure_sudoers
#         tags: ['sudoers']
#
#       - name: Run configured post-provision ansible task files.
#         include_tasks: "{{ outer_item }}"
#         loop_control:
#           loop_var: outer_item
#         with_fileglob: "{{ post_provision_tasks|default(omit) }}"
#         tags: ['post']
