#
#files/sshrc/
#├── sshrc
#└── sshrc.d
#    └── vimrc
#
- name: Create directories for sshrc
  ansible.builtin.file:
    path: "{{ cfg_home }}/sshrc"
    path: "{{ cfg_home }}/sshrc/sshrc.d"
    state: directory
    owner: "{{ user }}"
    mode: '0755'
#
#- name: Check directory.
#  stat:
#       #path: /Users/alx/test/zsh
#    path: "{{ cfg_home }}/nvim"
#    register: dst_folder
#
#- name: "echo if directory already existed"
#  debug:
#    msg: "the zsh config directory is already existed"
#  when: dst_folder.stat.exists
#
# Copy files
- name: Copy sshrc config files.
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    mode: u+rw,g+r,o+r
  loop:
    - { src: 'files/sshrc/sshrc', dest: "{{ cfg_home }}/sshrc/sshrc" }
    - { src: 'files/sshrc/sshrc.d/vimrc', dest: "{{ cfg_home }}/sshrc/sshrc.d" }

## Linking files
- name: Link files
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: "{{ cfg_home }}/sshrc/sshrc", dest: "{{ home }}/.sshrc" }
    - { src: "{{ cfg_home }}/sshrc/sshrc.d", dest: "{{ home }}/.sshrc.d" }
...


