# Install tmux config files
- name: Create a directory if it does not exist.
  ansible.builtin.file:
    path: "{{ cfg_home }}/tmux"
    state: directory
    owner: "{{ user }}"
    mode: '0755'

- name: Check directory.
  stat:
    path: "{{ cfg_home }}/tmux"
  register: dst_folder

- name: "echo if directory already existed"
  debug:
    msg: "the tmux config directory is already existed"
  when: dst_folder.stat.exists

# Copy files
- name: Copy tmux config file.
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    mode: u+rw,g+r,o+r
  loop:
    - { src: 'files/tmux/tmux.conf', dest: "{{ cfg_home }}/tmux" }

# Linking files
- name: Link files
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: "{{ cfg_home }}/tmux/tmux.conf", dest: "{{ home }}/.tmux.conf" }

