#  Install config vim
- name: Create a directory if it does not exist.
  ansible.builtin.file:
    path: "{{ cfg_home }}/vim"
    state: directory
    owner: "{{ user }}"
    mode: '0755'

- name: Check directory.
  stat:
    path: "{{ cfg_home }}/vim"
  register: dst_folder

- name: "echo if directory already existed"
  debug:
    msg: "the vim config directory is already existed"
  when: dst_folder.stat.exists

# Copy files
- name: Copy vim config file.
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    mode: u+rw,g+r,o+r
  loop:
    - { src: 'files/vim/vimrc', dest: "{{ cfg_home }}/vim" }

# Linking files
- name: Link files
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: "{{ cfg_home }}/vim/vimrc", dest: "{{ home }}/.vimrc" }





#  homebrew: name=neovim
#- pip:
#    name: neovim
#    executable: pip3
#    state: forcereinstall
#
#- name: Create a config directory
#  file:
#    path: ~/.config/nvim/
#    state: directory
#
#- name: Create a symlink for the vim config
#  file:
#    src: "{{ playbook_dir }}/../configs/init.vim"
#    path: ~/.config/nvim/init.vim
#    state: link
#    force: true
#
#- name: Create a directory for plugins
#  file:
#    path: ~/.config/nvim/autoload/
#    state: directory
#
#- name: Install vim-plug
#  get_url:
#    dest: ~/.config/nvim/autoload/plug.vim
#    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
