" minimal vimrc with no (extra) plugins
"
"load system defaults
if filereadable(expand('$VIMRUNTIME/defaults.vim'))
	unlet! g:skip_defaults_vim
	source $VIMRUNTIME/defaults.vim
endif

set ruler
set wildmenu
set showcmd
set showmatch
set number
set relativenumber

hi LineNr ctermfg=238 ctermbg=none
hi CursorLineNr cterm=none ctermbg=none ctermfg=none

" encoding/format
set encoding=utf-8 fileformats=unix,dos,mac

" searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" indent
set shiftwidth=4 tabstop=4 softtabstop=4
set autoindent

" key timeout values
set esckeys
set ttimeoutlen=20
set timeoutlen=1000

" allow syntax and filetype plugins
syntax enable
filetype plugin indent on

" autocmds
augroup general
    autocmd!
    "keep equal proportions when windows resized
    autocmd VimResized * wincmd =
    "save cursor position in a file
    autocmd BufReadPost * if line("'\"") > 1 && line("'\"")
                \ <= line("$") | exe "normal! g'\"" | endif
augroup END

augroup languages
    autocmd!
    autocmd BufNewFile,BufRead *.bash set syntax=sh
    autocmd FileType go set noexpandtab
    autocmd FileType html :syntax sync fromstart
    autocmd FileType python xnoremap <leader>r <esc>:'<,'>:w !python3<CR>
    autocmd FileType py,sh
                \ setlocal ts=4 sts=4 sw=4 expandtab
    autocmd FileType html,javascript,css,json,yaml,yml
                \ setlocal ts=2 sts=2 sw=2 expandtab
augroup END

" cursor shape change
let &t_SI.="\e[5 q" "SI = INSERT mode
let &t_SR.="\e[4 q" "SR = REPLACE mode
let &t_EI.="\e[2 q" "EI = NORMAL mode (ELSE)

" sudo write:
"command W w !sudo tee % >/dev/null
command W silent execute 'write !sudo tee ' . shellescape(@%, 1) . ' >/dev/null'

" <Leader>T = Delete all Trailing space in file
noremap <Leader>t :%s/\s\+$//<CR>:let @/=''<CR>:nohlsearch<CR>
noremap <Leader>w :w<CR>     " Save the current buffer using the leader key
noremap <Leader>e :wq<CR>    " Save and exit Vim using the leader key
noremap <Leader>q :q!<CR>    " Exit without saving using the leader key
