#!/usr/local/bin/zsh
# Global Aliases
# Suffix Aliases
# Functions for Aliases With Parameters
# Simple Aliases
# OS specific aliases ~~~> ~/.localrc

#
# Global Aliases  - ZSH global aliases for piping
#
alias -g C='| wc -l'
alias -g X='| xargs'
alias -g H='| head'
alias -g T='| tail'
alias -g L="| less"
alias -g S='| sort'
alias -g G='| grep -i'
alias -g F='| fzf'
alias -g LL="2>&1 | less"
alias -g CA="2>&1 | cat -A"
#
# Suffix Aliases  - Example ZSH clever aliases
#
alias -s {txt,yml,yaml}=nvim
alias -s {py,sh}=nvim
alias -s {md}=code
alias -s {json}=code
alias -s {html}=code
#
# Functions for Aliases With Parameters
#
mcd() { [ -n "$1" ] && mkdir -p "$1" && cd "$1"}    # Create directory and move into
cl()  { cd "$@" && ls -CF }                         # cd to a directory and ls
cdl() { cd "$@" && ls -CF }                         # cd to a directory and ls
dict() { open dict:///"$@" ; }                      # macOS dict. appl.
#
# Simple Aliases
#
alias .='pwd'
alias ~="cd ~/"
alias ..="cd .."
alias c='clear'                  # Clear terminal display
alias h='history'
alias m='make'                   #
alias v='nvim'                   #
alias vi='nvim'
alias vif='nvim $(fzf)'
# lists
alias l='ls -AF'                 # Compact view, show hidden
alias l.='ls -d .* '
alias ll='ls -alhF'
alias lt='ls -ltr'           #  Sort by date, most recent last.
alias lk='ls -lSr'           #  Sort by size, biggest last.
if [[ -x /usr/local/bin/exa ]]; then
   alias l='exa -F --group-directories-first'
   alias ls='exa -F --group-directories-first'
   alias la='exa -aF --group-directories-first'
   alias ll='exa -al --git --group-directories-first'
   alias let='exa -T'
fi
# Tree
alias tt="tree -L 2 -aC -I '.git |.DS_Store'"
alias ttt="tree -L 3 -aC -I '.git |.DS_Store'"
alias tre='tree -Ca'        # nice alternative to 'ls'
# Finding stuff!
alias fd='find . -type d -name'
alias ff='find . -type f -name'
#
alias df='df -kh'
alias f='open -a Finder ./'      # Opens current directory in MacOS Finder
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# alias Ansible
alias ans='ansible'
alias anp='ansible-playbook'
alias anv='ansible-vault --ask-vault-pass'
alias and='ansible-doc'                                                         
alias ang='ansible-galaxy'                                                     
alias anl='ansible-lint'                                                     

# alias for Terraform                                                             
alias tf='terraform'
alias tp='terraform plan'
alias ta='terraform apply'
alias ti='terraform init'

# Git aliases
alias g="git"
alias ga="git add"
alias gd="git diff"
alias gl="git pull"
alias gp="git push"
alias gst="git status"
alias gcmsg="git commit -m"
alias glog="git log --oneline --decorate --color --graph"

# Tmux aliases
alias tm='TERM=xterm-256color tmux'
alias tn='tmux new-session -s'                   # tmux new session
alias ta='tmux attach -t'                        # tmux attach
alias tl='tmux ls'                               # list
alias tk='tmux kill-session -s'                  # kill session name
alias td="tmux detach"
alias tmux='TERM=xterm-256color tmux'
#alias tml="tmux list-sessions"
#alias tma="tmux attach-session"
#
#
#
#export POWERSHELL_TELEMETRY_OPTOUT=1
#
#export PATH="/usr/local/opt/python@3.8/bin:$PATH"
#alias py='/usr/local/opt/python@3.8/bin/python3.8'
#export CPPFLAGS="-I/usr/local/opt/openjdk@11/include"
#export PATH="/usr/local/opt/openjdk@11/bin:$PATH"

