#
#{{{# Zgen              #
[[ -z $XDG_DATA_HOME ]] && echo 'data home not set' && return
if [[ ! -f $XDG_DATA_HOME/zsh/zgen/zgen.zsh ]]; then
  echo " ** zgen not found **"
  echo "Making $XDG_DATA_HOME/zsh if it doesn't exist..."
  mkdir -p $XDG_DATA_HOME/zsh
  echo "Downloading zgen..."
  git clone https://github.com/tarjoilija/zgen.git $XDG_DATA_HOME/zsh/zgen
fi
ZGEN_AUTOLOAD_COMPINIT=1
source $XDG_DATA_HOME/zsh/zgen/zgen.zsh
##
if ! zgen saved; then
    echo "Creating a zgen save"
    # Automatically run zgen update and zgen selfupdate every 7 days
    zgen load unixorn/autoupdate-zgen      
    zgen load zsh-users/zsh-completions src  
    zgen load BurntSushi/ripgrep complete
    zgen load zsh-users/zsh-autosuggestions
    ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=243'
    zgen load mafredri/zsh-async
    zgen load sindresorhus/pure
    zgen load junegunn/fzf shell
    zgen load urbainvaes/fzf-marks
    zgen save
fi
#}}}
#{{{# Options           #
# History command configuration
HIST_STAMPS="mm/dd/yyyy"
HISTFILE="$ZSH_CACHE/zhistory"
HISTSIZE=16384                 # size of the run-time history list
SAVEHIST=16384
export CLICOLOR=1
set -o vi                      # vi mode
setopt share_history           # share command history data
setopt extended_history        # Add timestamps to history
setopt inc_append_history      # add commands to HISTFILE in order of execution
setopt append_history          # Append history to existing file
setopt hist_expire_dups_first  # del duplic..s first when HISTFILE size HISTSIZE
setopt hist_ignore_dups        # ignore duplicated commands history list
setopt hist_ignore_space       # ignore commands that start with space
setopt hist_ignore_all_dups    # Remove the old entry and append the new one
setopt hist_verify             # show com.with history expansion before running it
setopt hist_find_no_dups       # Don't cycle through dupes
setopt hist_reduce_blanks      # Trim multiple blanks in history
setopt no_case_glob            # set ignore case for ls etc
#
setopt PUSHD_IGNORE_DUPS       # Don't duplicate dirs to the push/pop list
setopt auto_cd                 # automatically enter directories without cd
setopt auto_menu               # Use menu completion after the second completion reques    t
setopt auto_pushd              # Makes cd, pushd (cd +1, cd -1)
setopt always_to_end           # .. move the cursor to the end of the word
unsetopt beep                  # Don't beep
setopt complete_aliases        #  complete  ..
setopt complete_in_word        # Only complete when completion is confirmed
setopt correct                 # Try to autocorrect command
unsetopt correct_all           # Don't try to autocorrect all arguments
setopt interactive_comments    # Allow comments even in interactive shells
setopt local_options           # Allow functions to have local options
setopt local_traps             # Allow functions to have local traps
setopt menu_complete           # show completion on first tab
setopt multios                 # Allow multiple input/output redirection
setopt nohup                   # Don't kill background jobs on logout
setopt prompt_subst            # Enable parameter expansion, command substitution, etc.
setopt prompt_cr               # prompt always at beginning of line
setopt nonomatch               # Escape URL's special chars (eg.: ?)
setopt no_list_beep            # Don't beep on an ambiguous completion
export LSCOLORS=Gxfxcxdxbxegedabagacad   # ls colors

#}}}
#{{{# Completion        #

# Caching autocompletion
autoload -Uz compinit
#if [[ -n ~/.zcompdump(#qN.mh+24) ]]; then
if [[ -n $ZSH_CACHE/zcompdump(#qN.mh+24) ]]; then
  compinit -i
else
  compinit -C -i
fi
setopt COMPLETE_IN_WORD # Allow completion from within a word/phrase
setopt ALWAYS_TO_END    # When completing from the middle of a word, move cursor to end of word
setopt MENU_COMPLETE    # When using auto-complete, put the first option on the line immediately
setopt COMPLETE_ALIASES # Turn on completion for aliases as well
setopt LIST_ROWS_FIRST  # Cycle through menus horizontally instead of vertically
#
# Menu-like autocompletion selection
zmodload -i zsh/complist
# Automatically list choices on ambiguous completion
setopt auto_list
# Automatically use menu completion
setopt auto_menu
# Move cursor to end if word had one match
setopt always_to_end
# Select completions with arrow keys
zstyle ':completion:*' menu select
# Group results by category
zstyle ':completion:*' group-name ''
# Enable approximate matches for completion
zstyle ':completion:::::' completer _expand _complete _ignored _approximate
# Case and hyphen insensitive
zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|=*' 'l:|=* r:|=*'
# Use caching so that commands like apt and dpkg complete are useable
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion::complete:*' cache-path $ZSH_CACHE
# Make zsh know about hosts already accessed by SSH
zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync):hosts' hosts 'reply=(${=${${(f)"$(cat     {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'
#
# Add functions folder to $fpath array
fpath=($(brew --prefix)/share/zsh/functions \
       $(brew --prefix)/share/zsh-completions \
       $(brew --prefix)/share/zsh/site-functions $fpath)

#autoload bashcompinit && bashcompinit    # Enable bash completion

#}}}
#{{{# Aliases           #
# Globbing
setopt NO_CASE_GLOB       # Case insensitive globbing
setopt EXTENDED_GLOB      # Allow the powerful zsh globbing features, see link:
setopt NUMERIC_GLOB_SORT  # Sort globs that expand to numbers numerically, not by letter (i.e. 01 2 03)
#
# ZSH global aliases for piping
#alias -g C='| wc -l'
#alias -g X='| xargs'
#alias -g H='| head'
#alias -g T='| tail'
#alias -g L="| less"
#alias -g S='| sort'
#alias -g G='| grep -i'
#alias -g F='| fzf'
#alias -g LL="2>&1 | less"
#alias -g CA="2>&1 | cat -A"
# Example ZSH clever aliases
#alias -s {txt,yml,yaml}=nvim
# Aliases and functions
#alias .='pwd'
#alias ~="cd ~/"
#alias ..="cd .."
#alias c='clear'                  # Clear terminal display
#alias h='history'
#alias m='make'                   # 
#alias v='nvim'                   # 
#alias vi='nvim' 
#alias vif='nvim $(fzf)'
# lists
#alias l='ls -AF'                 # Compact view, show hidden
#alias l.='ls -d .* '
#alias ll='ls -alhF'
#alias lt='ls -ltr'           #  Sort by date, most recent last.
#alias lk='ls -lSr'           #  Sort by size, biggest last.
#if [[ -x /usr/local/bin/exa ]]; then
#   alias l='exa -F --group-directories-first'
#   alias ls='exa -F --group-directories-first'
#   alias la='exa -aF --group-directories-first'
#   alias ll='exa -al --git --group-directories-first'
#   alias let='exa -T'
#fi
# Tree
#alias tt='tree -L 2'
#alias ttt='tree -L 3'
#alias tre='tree -Ca'        # nice alternative to 'ls'
# Finding stuff!
#alias fd='find . -type d -name'
#a#lias ff='find . -type f -name'
# 
#alias df='df -kh'
#alias f='open -a Finder ./'      # Opens current directory in MacOS Finder
#alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"
# 
#mcd() { [ -n "$1" ] && mkdir -p "$1" && cd "$1"}    # Create directory and move into
#cl() { cd "$@" && ls -CF }                          # cd to a directory and ls
#dict() { open dict:///"$@" ; }                      # 
#}}}
#{{{# bindkey           #
# Find the key with: showkey -a
bindkey "^A"  beginning-of-line           # ctrl+a : move to beginning of line
bindkey "^E"  end-of-line                 # ctrl-e : move to end of line (e for end)
bindkey "^K"  vi-kill-eol                 # ctrl-k : delete from character to end of line
bindkey "^U"  kill-whole-line             # ctrl-u : clear line
bindkey "^R"  history-incremental-search-backward    # ctrl-r
bindkey "[D"  backward-word
bindkey "[C"  forward-word
# ctrl+b/f or ctrl+left/right : move word by word (backward/forward)
bindkey '^b'  backward-word               # ctrl + b : move to previous word (b for backward)
bindkey '^f'  forward-word                # ctrl + f : move to next word (f for forward)
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word
#
bindkey -s '^e' 'vim $(fzf)\n'
bindkey -s '^o' 'nvim $(fzf)\n'
#}}}
#{{{# prompt & fzf      #
autoload -U promptinit; promptinit
PURE_GIT_DOWN_ARROW=⇣
PURE_GIT_UP_ARROW=⇡
prompt pure
#
# fzf  
export FZF_CTRL_R_OPTS='--height 60%';
export FZF_ALT_C_OPTS='--height 60% --reverse';
export FZF_COMPLETION_OPTS='--height 40% --reverse';
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
#}}}
#
[ -f ${XDG_CONFIG_HOME}/zsh/alias.zsh ] && source ${XDG_CONFIG_HOME}/zsh/alias.zsh
[ -f ${XDG_CONFIG_HOME}/aliases ] && source ${XDG_CONFIG_HOME}/aliases
[ -f ${XDG_CONFIG_HOME}/functions ] && source ${XDG_CONFIG_HOME}/functions
[ -f ${HOME}/.localrc ] && source ${HOME}/.localrc
